// Design tokens, palettes, translations for East@West app

const PALETTES = {
  eastatwest: {
    name: 'East@West',
    light: {
      bg: '#EFF1E5',
      surface: '#F8F9EE',
      surfaceAlt: '#E0E4D2',
      ink: '#1A2419',
      inkSoft: '#4B5A48',
      inkMute: '#7E8B7A',
      line: 'rgba(26,36,25,0.10)',
      primary: '#1F5C2E',
      primaryInk: '#F8F9EE',
      olive: '#3F7841',
      accent: '#D9A93A',
      success: '#1F5C2E',
      danger: '#B23A2A',
    },
    dark: {
      bg: '#0F1A11',
      surface: '#16241A',
      surfaceAlt: '#1E2F22',
      ink: '#EDEFE0',
      inkSoft: '#B4C0A8',
      inkMute: '#7F8C78',
      line: 'rgba(237,239,224,0.10)',
      primary: '#5BA572',
      primaryInk: '#0F1A11',
      olive: '#90C297',
      accent: '#E5BD55',
      success: '#5BA572',
      danger: '#E0664F',
    },
  },
  terracotta: {
    name: 'Terracotta',
    light: {
      bg: '#F2EADB',
      surface: '#FAF4E6',
      surfaceAlt: '#EFE5D0',
      ink: '#2A2014',
      inkSoft: '#6F614A',
      inkMute: '#9D8C70',
      line: 'rgba(42,32,20,0.10)',
      primary: '#B85535',
      primaryInk: '#FFF5EC',
      olive: '#5A6A3F',
      accent: '#D9A246',
      success: '#5A6A3F',
      danger: '#B23A2A',
    },
    dark: {
      bg: '#1A140E',
      surface: '#241B12',
      surfaceAlt: '#2E2318',
      ink: '#F4EBD8',
      inkSoft: '#C5B49A',
      inkMute: '#8A7B64',
      line: 'rgba(244,235,216,0.10)',
      primary: '#D87A55',
      primaryInk: '#1A140E',
      olive: '#9CAF77',
      accent: '#E6B25C',
      success: '#9CAF77',
      danger: '#E0664F',
    },
  },
  olive: {
    name: 'Olive grove',
    light: {
      bg: '#EEEDDF',
      surface: '#F7F4E4',
      surfaceAlt: '#E5E2CE',
      ink: '#22241A',
      inkSoft: '#5C6049',
      inkMute: '#8E9277',
      line: 'rgba(34,36,26,0.10)',
      primary: '#4C5A3A',
      primaryInk: '#F4F1D8',
      olive: '#7A8758',
      accent: '#C28A2A',
      success: '#4C5A3A',
      danger: '#B23A2A',
    },
    dark: {
      bg: '#14150E',
      surface: '#1E1F15',
      surfaceAlt: '#2A2C1E',
      ink: '#EDEBD2',
      inkSoft: '#B7B898',
      inkMute: '#85876C',
      line: 'rgba(237,235,210,0.10)',
      primary: '#A8B27E',
      primaryInk: '#1A1A0F',
      olive: '#C2CB97',
      accent: '#E0A24A',
      success: '#A8B27E',
      danger: '#E0664F',
    },
  },
  saffron: {
    name: 'Saffron night',
    light: {
      bg: '#F6EFDF',
      surface: '#FCF7EA',
      surfaceAlt: '#EDE3CB',
      ink: '#2A1F12',
      inkSoft: '#6E5C44',
      inkMute: '#A0896A',
      line: 'rgba(42,31,18,0.10)',
      primary: '#C8842A',
      primaryInk: '#FFF6E2',
      olive: '#7A6638',
      accent: '#B23A2A',
      success: '#5A6A3F',
      danger: '#B23A2A',
    },
    dark: {
      bg: '#171108',
      surface: '#221A0F',
      surfaceAlt: '#2E2415',
      ink: '#F6E8C7',
      inkSoft: '#C6B188',
      inkMute: '#917D5A',
      line: 'rgba(246,232,199,0.10)',
      primary: '#E3A14A',
      primaryInk: '#1A1308',
      olive: '#C8A86B',
      accent: '#E0664F',
      success: '#A8B27E',
      danger: '#E0664F',
    },
  },
};

const T = {
  en: {
    // Tabs
    tab_home: 'Home',
    tab_reserve: 'Reserve',
    tab_order: 'Order',
    tab_account: 'You',
    // Home
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    home_subtitle: 'East@West, Brussels',
    home_open: 'Open today',
    home_hours: '12:00 – 14:30  ·  18:00 – 22:00',
    home_book: 'Book a table',
    home_book_sub: 'Tonight & beyond',
    home_order: 'Order takeaway',
    home_order_sub: 'Ready in 25 min',
    home_signature: 'Signature dishes',
    home_signature_sub: 'Our chef\u2019s picks this week',
    home_about: 'About us',
    home_about_text: 'At “East At West” we are dedicated to present the rich flavors, vibrant colors, and cultural heritage of Lebanese culinary traditions, in the heart of Brussels!',
    home_about_addr_l1: 'Bld de l\'Empereur 26',
    home_about_addr_l2: '1000 Brussels, Belgium',
    active_order: 'Active order',
    active_reservation: 'Tonight\u2019s reservation',
    track: 'Track',
    view: 'View',
    // Reserve
    res_title: 'Reserve a table',
    res_step: 'Step',
    res_of: 'of',
    res_q_party: 'How many guests?',
    res_q_party_sub: 'Up to 22 guests — for larger groups, please call us',
    res_guest: 'guest',
    res_guests: 'guests',
    res_larger_party: 'Larger party',
    res_q_date: 'Pick a date',
    res_q_date_sub: 'Available for the next 30 days',
    res_q_time: 'Pick a time',
    res_q_time_sub: 'All times in Brussels (CET)',
    res_lunch: 'Lunch',
    res_dinner: 'Dinner',
    res_range_pick_start: 'Pick a start time',
    res_range_pick_end: 'Now pick an end time',
    res_tonight: 'Tonight',
    res_tomorrow: 'Tomorrow',
    res_weekend: 'This weekend',
    res_duration: 'Duration',
    res_no_slots: 'No tables available — try another date',
    res_q_details: 'Your details',
    res_q_details_sub: 'We\u2019ll text you the confirmation',
    res_name: 'Full name',
    res_phone: 'Phone',
    res_email: 'Email',
    res_occasion: 'Occasion',
    res_occasion_none: 'Just dinner',
    res_occasion_birthday: 'Birthday',
    res_occasion_anniv: 'Anniversary',
    res_occasion_business: 'Business',
    res_occasion_date: 'Date night',
    res_notes: 'Allergies, dietary needs, requests',
    res_notes_ph: 'e.g. vegetarian, gluten-free, window seat\u2026',
    res_review: 'Review your reservation',
    res_review_sub: 'You can change or cancel up to 2 hours before',
    res_confirm: 'Confirm reservation',
    res_done_title: 'You\u2019re booked',
    res_done_sub: 'A confirmation has been sent to your phone',
    res_pending_title: 'Reservation pending',
    res_pending_sub: 'Parties of 7 or more need our manager’s approval. We’ll text you within an hour.',
    res_pending_badge: 'Awaiting approval',
    res_done_code: 'Confirmation',
    res_add_calendar: 'Add to calendar',
    res_directions: 'Get directions',
    res_back_home: 'Back to home',
    // Takeaway
    ord_title: 'Order takeaway',
    ord_search: 'Search the menu',
    ord_cat_sets: 'Set Menus',
    ord_cat_lunch: 'Lunch Dishes',
    ord_cat_mezze: 'Cold Mezze',
    ord_cat_salads: 'Salads',
    ord_cat_hot: 'Hot Mezze',
    ord_cat_sandwiches: 'Sandwiches',
    ord_cat_grill: 'From the Grill',
    ord_cat_sides: 'Sides & Bread',
    ord_cat_desserts: 'Desserts',
    ord_cat_drinks: 'Drinks',
    ord_popular: 'Popular this week',
    ord_add: 'Add',
    ord_added: 'Added',
    ord_view_cart: 'View basket',
    ord_item: 'item',
    ord_items: 'items',
    ord_customise: 'Customise',
    ord_spice: 'Spice level',
    ord_spice_mild: 'Mild',
    ord_spice_med: 'Medium',
    ord_spice_hot: 'Hot',
    ord_extras: 'Add extras',
    ord_qty: 'Quantity',
    ord_add_to_cart: 'Add to basket',
    ord_cart: 'Your basket',
    ord_subtotal: 'Subtotal',
    ord_tax: 'VAT 12%',
    ord_total: 'Total',
    ord_continue: 'Continue',
    ord_empty: 'Your basket is empty',
    ord_empty_sub: 'Browse the menu and add a few dishes',
    ord_pickup_title: 'When should it be ready?',
    ord_pickup_sub: 'We need 25 minutes minimum',
    ord_pickup_asap: 'As soon as possible',
    ord_pickup_asap_sub: 'Ready ~ ',
    ord_pickup_pick: 'Pick a time',
    ord_pay_title: 'Payment',
    ord_pay_sub: 'Tap to confirm',
    ord_pay_apple: 'Pay with Apple Pay',
    ord_pay_google: 'Pay with Google Pay',
    ord_pay_card: 'Pay by card',
    ord_pay_change: 'Change payment',
    ord_done_title: 'Order placed',
    ord_done_sub: 'Show this code when you collect',
    ord_done_eta: 'Ready by',
    ord_done_addr: 'Bld de l\'Empereur 26, 1000 Brussels',
    ord_track_order: 'Track order',
    // Order tracking
    track_title: 'Your order',
    track_status_received: 'Received',
    track_status_prep: 'Preparing',
    track_status_ready: 'Ready for pickup',
    track_status_collected: 'Collected',
    track_eta: 'Ready by',
    track_items: 'Items',
    track_total_paid: 'Paid',
    track_call: 'Call restaurant',
    track_cancel: 'Cancel order',
    // Account
    acc_title: 'You',
    acc_signin: 'Sign in for faster ordering',
    acc_member: 'Member since',
    acc_orders: 'Past orders',
    acc_reservations: 'Past reservations',
    acc_settings: 'Settings',
    acc_addresses: 'Saved addresses',
    acc_payment: 'Payment methods',
    acc_lang: 'Language',
    acc_notifications: 'Notifications',
    acc_help: 'Help',
    acc_signout: 'Sign out',
    acc_reorder: 'Re-order',
    // Common
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    optional: 'optional',
    required: 'required',
    today: 'Today',
    tomorrow: 'Tomorrow',
    minutes: 'min',
  },
  fr: {
    tab_home: 'Accueil',
    tab_reserve: 'R\u00e9server',
    tab_order: 'Commander',
    tab_account: 'Vous',
    greeting_morning: 'Bonjour',
    greeting_afternoon: 'Bon apr\u00e8s-midi',
    greeting_evening: 'Bonsoir',
    home_subtitle: 'East@West, Bruxelles',
    home_open: 'Ouvert aujourd\u2019hui',
    home_hours: '12h00 – 14h30  ·  18h00 – 22h00',
    home_book: 'R\u00e9server une table',
    home_book_sub: 'Ce soir et apr\u00e8s',
    home_order: 'Commander \u00e0 emporter',
    home_order_sub: 'Pr\u00eat en 25 min',
    home_signature: 'Plats signatures',
    home_signature_sub: 'Les choix du chef cette semaine',
    home_about: 'À propos',
    home_about_text: 'Chez « East At West », nous mettons à l’honneur les saveurs riches, les couleurs vibrantes et l’héritage culturel des traditions culinaires libanaises, au cœur de Bruxelles !',
    home_about_addr_l1: 'Bld de l\'Empereur 26',
    home_about_addr_l2: '1000 Bruxelles, Belgique',
    active_order: 'Commande en cours',
    active_reservation: 'R\u00e9servation ce soir',
    track: 'Suivre',
    view: 'Voir',
    res_title: 'R\u00e9server une table',
    res_step: '\u00c9tape',
    res_of: 'sur',
    res_q_party: 'Combien d\u2019invit\u00e9s ?',
    res_q_party_sub: 'Jusqu’à 22 personnes — au-delà, appelez-nous',
    res_guest: 'personne',
    res_guests: 'personnes',
    res_larger_party: 'Grand groupe',
    res_q_date: 'Choisir une date',
    res_q_date_sub: 'Disponible les 30 prochains jours',
    res_q_time: 'Choisir un horaire',
    res_q_time_sub: 'Heures de Bruxelles (CET)',
    res_lunch: 'D\u00e9jeuner',
    res_dinner: 'D\u00eener',
    res_range_pick_start: 'Choisissez l\u2019heure d\u2019arriv\u00e9e',
    res_range_pick_end: 'Choisissez l\u2019heure de d\u00e9part',
    res_tonight: 'Ce soir',
    res_tomorrow: 'Demain',
    res_weekend: 'Ce week-end',
    res_duration: 'Dur\u00e9e',
    res_no_slots: 'Aucune table disponible — essayez une autre date',
    res_q_details: 'Vos coordonn\u00e9es',
    res_q_details_sub: 'Nous vous enverrons la confirmation par SMS',
    res_name: 'Nom complet',
    res_phone: 'T\u00e9l\u00e9phone',
    res_email: 'E-mail',
    res_occasion: 'Occasion',
    res_occasion_none: 'Simple d\u00eener',
    res_occasion_birthday: 'Anniversaire',
    res_occasion_anniv: 'Anniversaire de mariage',
    res_occasion_business: 'Affaires',
    res_occasion_date: 'En amoureux',
    res_notes: 'Allergies, r\u00e9gimes, demandes',
    res_notes_ph: 'ex. v\u00e9g\u00e9tarien, sans gluten, pr\u00e8s de la fen\u00eatre\u2026',
    res_review: 'Votre r\u00e9servation',
    res_review_sub: 'Modifiable ou annulable jusqu\u2019\u00e0 2h avant',
    res_confirm: 'Confirmer',
    res_done_title: 'C\u2019est r\u00e9serv\u00e9',
    res_done_sub: 'Confirmation envoy\u00e9e sur votre t\u00e9l\u00e9phone',
    res_pending_title: 'Réservation en attente',
    res_pending_sub: 'Les groupes de 7 personnes ou plus nécessitent l’approbation du responsable. Nous vous répondrons sous une heure.',
    res_pending_badge: 'En attente d’approbation',
    res_done_code: 'Confirmation',
    res_add_calendar: 'Ajouter au calendrier',
    res_directions: 'Itin\u00e9raire',
    res_back_home: 'Retour \u00e0 l\u2019accueil',
    ord_title: 'Commander \u00e0 emporter',
    ord_search: 'Rechercher dans le menu',
    ord_cat_sets: 'Menus',
    ord_cat_lunch: 'Plats du midi',
    ord_cat_mezze: 'Mezze froids',
    ord_cat_salads: 'Salades',
    ord_cat_hot: 'Mezze chauds',
    ord_cat_sandwiches: 'Sandwichs',
    ord_cat_grill: 'Grillades',
    ord_cat_sides: 'Pains & accompagn.',
    ord_cat_desserts: 'Desserts',
    ord_cat_drinks: 'Boissons',
    ord_popular: 'Populaires cette semaine',
    ord_add: 'Ajouter',
    ord_added: 'Ajout\u00e9',
    ord_view_cart: 'Voir le panier',
    ord_item: 'article',
    ord_items: 'articles',
    ord_customise: 'Personnaliser',
    ord_spice: 'Piquant',
    ord_spice_mild: 'Doux',
    ord_spice_med: 'Moyen',
    ord_spice_hot: 'Fort',
    ord_extras: 'Suppl\u00e9ments',
    ord_qty: 'Quantit\u00e9',
    ord_add_to_cart: 'Ajouter au panier',
    ord_cart: 'Votre panier',
    ord_subtotal: 'Sous-total',
    ord_tax: 'TVA 12%',
    ord_total: 'Total',
    ord_continue: 'Continuer',
    ord_empty: 'Votre panier est vide',
    ord_empty_sub: 'Parcourez le menu et ajoutez des plats',
    ord_pickup_title: 'Pour quelle heure ?',
    ord_pickup_sub: 'Pr\u00e9voyez 25 minutes minimum',
    ord_pickup_asap: 'D\u00e8s que possible',
    ord_pickup_asap_sub: 'Pr\u00eat vers ',
    ord_pickup_pick: 'Choisir une heure',
    ord_pay_title: 'Paiement',
    ord_pay_sub: 'Touchez pour confirmer',
    ord_pay_apple: 'Payer avec Apple Pay',
    ord_pay_google: 'Payer avec Google Pay',
    ord_pay_card: 'Payer par carte',
    ord_pay_change: 'Changer de moyen',
    ord_done_title: 'Commande pass\u00e9e',
    ord_done_sub: 'Pr\u00e9sentez ce code au retrait',
    ord_done_eta: 'Pr\u00eat \u00e0',
    ord_done_addr: 'Bld de l\'Empereur 26, 1000 Bruxelles',
    ord_track_order: 'Suivre la commande',
    track_title: 'Votre commande',
    track_status_received: 'Re\u00e7ue',
    track_status_prep: 'En pr\u00e9paration',
    track_status_ready: 'Pr\u00eate au retrait',
    track_status_collected: 'R\u00e9cup\u00e9r\u00e9e',
    track_eta: 'Pr\u00eat \u00e0',
    track_items: 'Articles',
    track_total_paid: 'Pay\u00e9',
    track_call: 'Appeler',
    track_cancel: 'Annuler',
    acc_title: 'Vous',
    acc_signin: 'Connectez-vous pour commander plus vite',
    acc_member: 'Membre depuis',
    acc_orders: 'Commandes pass\u00e9es',
    acc_reservations: 'R\u00e9servations pass\u00e9es',
    acc_settings: 'Param\u00e8tres',
    acc_addresses: 'Adresses enregistr\u00e9es',
    acc_payment: 'Moyens de paiement',
    acc_lang: 'Langue',
    acc_notifications: 'Notifications',
    acc_help: 'Aide',
    acc_signout: 'Se d\u00e9connecter',
    acc_reorder: 'Recommander',
    next: 'Suivant',
    back: 'Retour',
    skip: 'Passer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    optional: 'facultatif',
    required: 'requis',
    today: 'Aujourd\u2019hui',
    tomorrow: 'Demain',
    minutes: 'min',
  },
  nl: {
    // Tabs
    tab_home: 'Start',
    tab_reserve: 'Reserveren',
    tab_order: 'Bestellen',
    tab_account: 'Jij',
    // Home
    greeting_morning: 'Goedemorgen',
    greeting_afternoon: 'Goedemiddag',
    greeting_evening: 'Goedenavond',
    home_subtitle: 'East@West, Brussel',
    home_open: 'Vandaag open',
    home_hours: '12:00 \u2013 14:30  \u00b7  18:00 \u2013 22:00',
    home_book: 'Tafel reserveren',
    home_book_sub: 'Vanavond en later',
    home_order: 'Afhalen bestellen',
    home_order_sub: 'Klaar in 25 min',
    home_signature: 'Signatuurgerechten',
    home_signature_sub: 'De keuze van onze chef deze week',
    home_about: 'Over ons',
    home_about_text: 'Bij \u00ab East At West \u00bb presenteren we met passie de rijke smaken, levendige kleuren en culturele erfenis van de Libanese culinaire tradities, in het hart van Brussel!',
    home_about_addr_l1: 'Bld de l\'Empereur 26',
    home_about_addr_l2: '1000 Brussel, Belgi\u00eb',
    active_order: 'Actieve bestelling',
    active_reservation: 'Reservering vanavond',
    track: 'Volgen',
    view: 'Bekijken',
    // Reserve
    res_title: 'Tafel reserveren',
    res_step: 'Stap',
    res_of: 'van',
    res_q_party: 'Hoeveel gasten?',
    res_q_party_sub: 'Tot 22 gasten — voor grotere groepen, bel ons',
    res_guest: 'gast',
    res_guests: 'gasten',
    res_larger_party: 'Grote groep',
    res_q_date: 'Kies een datum',
    res_q_date_sub: 'Beschikbaar de komende 30 dagen',
    res_q_time: 'Kies een tijdstip',
    res_q_time_sub: 'Alle tijden in Brussel (CET)',
    res_lunch: 'Lunch',
    res_dinner: 'Diner',
    res_range_pick_start: 'Kies een aankomsttijd',
    res_range_pick_end: 'Kies nu een eindtijd',
    res_tonight: 'Vanavond',
    res_tomorrow: 'Morgen',
    res_weekend: 'Dit weekend',
    res_duration: 'Duur',
    res_no_slots: 'Geen tafels beschikbaar \u2014 probeer een andere datum',
    res_q_details: 'Uw gegevens',
    res_q_details_sub: 'We sturen u een bevestiging per sms',
    res_name: 'Volledige naam',
    res_phone: 'Telefoon',
    res_email: 'E-mail',
    res_occasion: 'Gelegenheid',
    res_occasion_none: 'Gewoon dineren',
    res_occasion_birthday: 'Verjaardag',
    res_occasion_anniv: 'Jubileum',
    res_occasion_business: 'Zakelijk',
    res_occasion_date: 'Romantische avond',
    res_notes: 'Allergie\u00ebn, dieetwensen, verzoeken',
    res_notes_ph: 'bv. vegetarisch, glutenvrij, plaats bij het raam\u2026',
    res_review: 'Controleer uw reservering',
    res_review_sub: 'Wijzigen of annuleren kan tot 2 uur vooraf',
    res_confirm: 'Bevestigen',
    res_done_title: 'Uw reservering is bevestigd',
    res_done_sub: 'Een bevestiging is naar uw telefoon gestuurd',
    res_pending_title: 'Reservering in behandeling',
    res_pending_sub: 'Groepen van 7 personen of meer hebben goedkeuring van onze manager nodig. U hoort binnen een uur van ons.',
    res_pending_badge: 'In afwachting van goedkeuring',
    res_done_code: 'Bevestiging',
    res_add_calendar: 'Aan agenda toevoegen',
    res_directions: 'Routebeschrijving',
    res_back_home: 'Terug naar start',
    // Takeaway
    ord_title: 'Afhalen bestellen',
    ord_search: 'Zoek in het menu',
    ord_cat_sets: 'Menu\'s',
    ord_cat_lunch: 'Lunchgerechten',
    ord_cat_mezze: 'Koude mezze',
    ord_cat_salads: 'Salades',
    ord_cat_hot: 'Warme mezze',
    ord_cat_sandwiches: 'Sandwiches',
    ord_cat_grill: 'Van de grill',
    ord_cat_sides: 'Bijgerechten & brood',
    ord_cat_desserts: 'Desserts',
    ord_cat_drinks: 'Dranken',
    ord_popular: 'Populair deze week',
    ord_add: 'Toevoegen',
    ord_added: 'Toegevoegd',
    ord_view_cart: 'Mandje bekijken',
    ord_item: 'artikel',
    ord_items: 'artikelen',
    ord_customise: 'Aanpassen',
    ord_spice: 'Pittigheid',
    ord_spice_mild: 'Mild',
    ord_spice_med: 'Medium',
    ord_spice_hot: 'Pittig',
    ord_extras: 'Extra\'s toevoegen',
    ord_qty: 'Aantal',
    ord_add_to_cart: 'In mandje',
    ord_cart: 'Uw mandje',
    ord_subtotal: 'Subtotaal',
    ord_tax: 'BTW 12%',
    ord_total: 'Totaal',
    ord_continue: 'Doorgaan',
    ord_empty: 'Uw mandje is leeg',
    ord_empty_sub: 'Blader door het menu en voeg gerechten toe',
    ord_pickup_title: 'Wanneer moet het klaar zijn?',
    ord_pickup_sub: 'Wij hebben minstens 25 minuten nodig',
    ord_pickup_asap: 'Zo snel mogelijk',
    ord_pickup_asap_sub: 'Klaar ~ ',
    ord_pickup_pick: 'Kies een tijdstip',
    ord_pay_title: 'Betaling',
    ord_pay_sub: 'Tik om te bevestigen',
    ord_pay_apple: 'Betaal met Apple Pay',
    ord_pay_google: 'Betaal met Google Pay',
    ord_pay_card: 'Betaal met kaart',
    ord_pay_change: 'Betaalmiddel wijzigen',
    ord_done_title: 'Bestelling geplaatst',
    ord_done_sub: 'Toon deze code bij het afhalen',
    ord_done_eta: 'Klaar om',
    ord_done_addr: 'Bld de l\'Empereur 26, 1000 Brussel',
    ord_track_order: 'Bestelling volgen',
    // Order tracking
    track_title: 'Uw bestelling',
    track_status_received: 'Ontvangen',
    track_status_prep: 'In bereiding',
    track_status_ready: 'Klaar om af te halen',
    track_status_collected: 'Afgehaald',
    track_eta: 'Klaar om',
    track_items: 'Artikelen',
    track_total_paid: 'Betaald',
    track_call: 'Restaurant bellen',
    track_cancel: 'Bestelling annuleren',
    // Account
    acc_title: 'Jij',
    acc_signin: 'Meld u aan voor sneller bestellen',
    acc_member: 'Lid sinds',
    acc_orders: 'Eerdere bestellingen',
    acc_reservations: 'Eerdere reserveringen',
    acc_settings: 'Instellingen',
    acc_addresses: 'Opgeslagen adressen',
    acc_payment: 'Betaalmethoden',
    acc_lang: 'Taal',
    acc_notifications: 'Meldingen',
    acc_help: 'Help',
    acc_signout: 'Afmelden',
    acc_reorder: 'Opnieuw bestellen',
    // Common
    next: 'Volgende',
    back: 'Terug',
    skip: 'Overslaan',
    cancel: 'Annuleren',
    save: 'Opslaan',
    edit: 'Bewerken',
    optional: 'optioneel',
    required: 'verplicht',
    today: 'Vandaag',
    tomorrow: 'Morgen',
    minutes: 'min',
  },
};

// Language metadata — display label + locale codes that map to each app lang
const LANGS = [
  { id: 'en', label: 'English',    short: 'EN', locales: ['en'] },
  { id: 'fr', label: 'Fran\u00e7ais',   short: 'FR', locales: ['fr'] },
  { id: 'nl', label: 'Nederlands', short: 'NL', locales: ['nl'] },
];

// Detect a sensible default language from browser locale, fallback to 'en'
function detectLang() {
  if (typeof navigator === 'undefined') return 'en';
  const candidates = [navigator.language, ...(navigator.languages || [])].filter(Boolean);
  for (const loc of candidates) {
    const code = loc.toLowerCase().split(/[-_]/)[0];
    const match = LANGS.find(l => l.locales.includes(code));
    if (match) return match.id;
  }
  return 'en';
}

Object.assign(window, { PALETTES, T, LANGS, detectLang });
